print('**************')
num1=44.11
num2=61.23
print('Addition')
sum=float(num1+num2)
print('addition answert in float ={2}'.format(num1,num2,sum))
sum=int(num1+num2)
print('addition answert in int ={2}'.format(num1,num2,sum))
print('**************')
print('Subtraction')
sub=float(num1-num2)
print('subtraction answert in float ={2}'.format(num1,num2,sub))
sub=int(num1-num2)
print('subtraction answert in int ={2}'.format(num1,num2,sub))
print('**************')
print('Multiplication')
mul=float(num1*num2)
print('multiplication answert in float ={2}'.format(num1,num2,mul))
mul=int(num1*num2)
print('multiplication answert in int ={2}'.format(num1,num2,mul))
print('**************')
print('division-quotient')
div=float(num1/num2)
print('division-quotient answert in float ={2}'.format(num1,num2,div))
div=int(num1/num2)
print('division-quotient answert in int ={2}'.format(num1,num2,div))
print('**************')
print('division-remainder')
rem=float(num1%num2)
print('division-remainder answert in float ={2}'.format(num1,num2,rem))
rem=int(num1%num2)
print('division-remainder answert in int ={2}'.format(num1,num2,rem))
