print('**************')
num1=input("enter a number as integer")
num2=input("enter a number as integer")
num3=input("enter a number as float")
num4=input("enter a number as floatr")



print('Addition')
sum=float(num3)+float(num4)
print('addition answert in float ={2}'.format(num1,num2,sum))
sum=int(num1)+int(num2)
print('addition answert in int ={2}'.format(num1,num2,sum))
print('**************')
print('Subtraction')
sub=float(num3)-float(num4)
print('subtraction answert in float ={2}'.format(num1,num2,sub))
sub=int(num1)-int(num2)
print('subtraction answert in int ={2}'.format(num1,num2,sub))
print('**************')
print('Multiplication')
mul=float(num3)*float(num4)
print('multiplication answert in float ={2}'.format(num1,num2,mul))
mul=int(num1)*int(num2)
print('multiplication answert in int ={2}'.format(num1,num2,mul))
print('**************')
print('division-quotient')
div=float(num3)/float(num4)
print('division-quotient answert in float ={2}'.format(num1,num2,div))
div=int(num1)/int(num2)
print('division-quotient answert in int ={2}'.format(num1,num2,div))
print('**************')
print('division-remainder')
rem=float(num3)%float(num4)
print('division-remainder answert in float ={2}'.format(num1,num2,rem))
rem=int(num1)%int(num2)
print('division-remainder answert in int ={2}'.format(num1,num2,rem))

