x=["apple","banana"]
print(x)
print("apple in x :", end=" ")
print("apple"in x)
print("grape in x :",end=" ")
print("grape"in x)
print("appleis x:",end=" ")
print("apple"is x)
print("grapeis x:",end=" ")
print("grape"is x)
print("appleis not x:",end=" ")
print("apple"is not x)
print("grapeis not x:",end=" ")
print("grape"is not x)
